### ISSUE TITLE
Wishlist: add at least the other base enemies? (eg.: bees)

### ISSUE THREAD

**Issue by NeatWolf** [Ian0526/KillableEnemies#4]
Hi, apologies for opening a bug request here but I didn't find a Discord link to post on.

I've been happily using your mod for a while, since the EverythingCanDie mod causes issues and desyncs (clients still see the enemies standing and alive).

Yet, is there any chance you could expand the list to include a full list of the base enemies?

**Comment by Ian0526** [comment]
Hey Neat, I've had a couple of people come forward requesting the same. I'll try and make time to add them in. Thanks for the message.

**Comment by NeatWolf** [comment]
Much appreciated! Thanks for your time! In another situation I'd have asked if I could fork the repo, but I'm still badly burnt-out by doing too much BG3 modding to embrace LC modding as well. I totally understand you if you feel to take a break. Hopefully expanding the list isn't going require any enemy-specific hack!
